spring:
  application:
    name: smallChese
  datasource:
        name: smallChese
        url: jdbc:mysql://cdb-6k8q46bp.gz.tencentcdb.com:10127/manuscript?characterEncoding=utf-8&useSSL=true
        username: root
        password: C2eGdA6n8i@()
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
  http:
    encoding:
      force: true
      charset: UTF-8
  
mybatis: 
  mapper-locations: classpath:/mapper/*.xml
  
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    
http: 
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 10000
  connectionRequestTimeout: 1000
  socketTimeout: 10000000
  
  